"""init

Revision ID: 865f64274d3e
Revises: 
Create Date: 2019-05-08 14:05:02.859617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '865f64274d3e'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_access_tokens'))
    )
    op.create_index('token_index', 'access_tokens', ['token'], unique=True, mysql_length=255)
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_models'))
    )
    op.create_index('my_index', 'models', ['name'], unique=True, mysql_length=255)
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('purl', sa.Text(), nullable=True),
    sa.Column('auth', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services'))
    )
    op.create_index('name_index', 'services', ['name'], unique=True, mysql_length=255)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name_index', table_name='services')
    op.drop_table('services')
    op.drop_index('my_index', table_name='models')
    op.drop_table('models')
    op.drop_index('token_index', table_name='access_tokens')
    op.drop_table('access_tokens')
    # ### end Alembic commands ###
